# Generated by Django 3.2.4 on 2021-06-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_photo', models.ImageField(null=True, upload_to='')),
                ('employee_fullname', models.CharField(default='', max_length=300)),
                ('employee_specialization', models.CharField(default='', max_length=300)),
                ('employee_email', models.EmailField(default='example@mail.com', max_length=300)),
                ('employee_info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_email', models.EmailField(max_length=254, null=True)),
                ('order_title', models.CharField(max_length=200, null=True)),
                ('order_number', models.CharField(max_length=200, null=True)),
                ('order_name', models.CharField(max_length=200, null=True)),
                ('order_info', models.TextField(null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_photo_main', models.ImageField(null=True, upload_to='')),
                ('work_photo_2', models.ImageField(null=True, upload_to='')),
                ('work_photo_3', models.ImageField(null=True, upload_to='')),
                ('work_title', models.CharField(max_length=200, null=True)),
                ('work_info', models.TextField(null=True)),
                ('work_address', models.CharField(default='https://', max_length=300, null=True)),
            ],
        ),
    ]
