# Generated by Django 3.2.4 on 2021-06-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstudio', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(default='example@mail.com', max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_fullname',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_specialization',
            field=models.CharField(default='', max_length=300),
        ),
    ]
