# Generated by Django 3.2.4 on 2021-06-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstudio', '0002_order_order_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
