# Generated by Django 3.2.4 on 2021-06-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstudio', '0003_auto_20210613_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_contacts',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
