# Generated by Django 3.2.4 on 2021-06-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstudio', '0004_auto_20210613_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='work_address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='works',
            name='work_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='works',
            name='work_photo_2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='works',
            name='work_photo_3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='works',
            name='work_photo_main',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='works',
            name='work_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
