# Generated by Django 3.2.4 on 2021-06-14 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webstudio', '0006_alter_works_work_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 16, 25, 42, 979404, tzinfo=utc)),
        ),
    ]
